version: '{build}'

image: Visual Studio 2017

skip_tags: true
clone_depth: 1

configuration: Release
platform: Any CPU

before_build:
  - nuget restore src/Simplify.sln

build:
  project: src/Simplify.sln
  publish_nuget: true
  parallel: true
  verbosity: minimal

test:
  categories:
    except:
      - Integration

deploy_script:
 - ps: .\MakeSourcePackages.ps1
